### ISSUE TITLE
detect the gflags namespace

### ISSUE THREAD

**Issue by pphaneuf** [google/certificate-transparency#1035] opened 2015-11-06 17:01 UTC
Sometimes gflags is in `google`, sometimes it's in `gflags`. Cook up an autoconf test to figure it out, and add a little header to do something appropriate for us.

**Comment by philandstuff** [comment] 2015-11-18 09:57
dupe of #723?

**Comment by benlaurie** [comment] 2015-11-18 10:50
Correct, this is a dupe of #723.

**Closed by benlaurie** 2015-11-18 10:50 UTC
