### ISSUE TITLE
The log server frequently crash when the master election.

### ISSUE THREAD

**Issue by tedwang2015** [google/certificate-transparency#811] opened 2015-07-02 03:31 UTC
The log server frequently crash for the master election.  

Please see the stack trace below. 

Environment ct log + etcd. 

```text
F0701 09:15:11.091508 22393 masterelection.cc:363] Check failed: task->status().ok() /root/election/c0b90f7d-a261-4a9e-9887-d9fdb5710ab9: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
*** Check failure stack trace: ***
    @     0x7fcc585ae20d  google::LogMessage::Fail()
    @     0x7fcc585affac  google::LogMessage::SendToLog()
    @     0x7fcc585ade2b  google::LogMessage::Flush()
    @     0x7fcc585b08be  google::LogMessageFatal::~LogMessageFatal()
    @           0x4f4952  cert_trans::MasterElection::ProposalUpdateDone()
    @           0x4fb0e5  _ZNKSt7_Mem_fnIMN10cert_trans14MasterElectionEFvRKSsPNS0_10EtcdClient8ResponseEPN4util4TaskEEEclIJRSsRS6_S9_EvEEvPS1_DpOT_
    @           0x4fab74  _ZNSt5_BindIFSt7_Mem_fnIMN10cert_trans14MasterElectionEFvRKSsPNS1_10EtcdClient8ResponseEPN4util4TaskEEEPS2_SsS7_St12_PlaceholderILi1EEEE6__callIvJOSA_EJLm0ELm1ELm2ELm3EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @           0x4fa031  _ZNSt5_BindIFSt7_Mem_fnIMN10cert_trans14MasterElectionEFvRKSsPNS1_10EtcdClient8ResponseEPN4util4TaskEEEPS2_SsS7_St12_PlaceholderILi1EEEEclIJSA_EvEET0_DpOT_
    @           0x4f938d  std::_Function_handler<>::_M_invoke()
    @           0x4fe77f  std::function<>::operator()()
    @           0x4fd725  util::Task::RunCleanupAndDoneCallbacks()
    @           0x500b5f  _ZNKSt7_Mem_fnIMN4util4TaskEFvvEEclIIEvEEvPS1_DpOT_
    @           0x5007be  _ZNSt5_BindIFSt7_Mem_fnIMN4util4TaskEFvvEEPS2_EE6__callIvIEILm0EEEET_OSt5tupleIIDpT0_EESt12_Index_tupleIIXspT1_EEE
    @           0x500130  _ZNSt5_BindIFSt7_Mem_fnIMN4util4TaskEFvvEEPS2_EEclIJEvEET0_DpOT_
    @           0x4ff805  std::_Function_handler<>::_M_invoke()
    @           0x45233c  std::function<>::operator()()
    @           0x4505cb  cert_trans::libevent::Base::RunClosures()
    @     0x7fcc598a75b4  event_base_loop
    @           0x4500e2  cert_trans::libevent::Base::Dispatch()
    @           0x427fa5  cert_trans::Server<>::Run()
    @           0x4238d2  main
    @     0x7fcc57435d5d  __libc_start_main
    @           0x40e829  (unknown)
```

**Comment by AlCutter** [comment] 2015-07-02 08:26
Hi Ted,

It might be worth running with `-v 2`  to see exactly what's being returned by etcd in this case. 

Also, can you make sure you're up to date with HEAD as there have been a couple of updates recently in this area?

**Comment by pphaneuf** [comment] 2015-07-02 10:27
And, specifically, improved error reporting! In the older version that you're running, `FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'` is a fairly generic error that could mean many things, but @AlCutter improved the reporting to actually say what is wrong (as best we can tell), which will help debugging.

**Comment by tedwang2015** [comment] 2015-07-13 02:26
So the i would pull the latest code set the v=1, keep monitor right?

**Comment by pphaneuf** [comment] 2015-07-13 09:33
On Mon, Jul 13, 2015 at 3:26 AM, tedwang2015 <notifications@github.com> wrote:

> So the i would pull the latest code set the v=1, keep monitor right?

You can check that you have pulled a recent enough version by running
"ct-server --version" (no other flag), and seeing output like this:

$ cpp/server/ct-server --version
ct-server version 7755371ff02e696fea5978367012b8560b562a17

If you see just "ct-server", without the "version
7755371ff02e696fea5978367012b8560b562a17" part, it means you really
need to update.

This version string is a newly added feature, to help identify what
people are running. If you have other problems, it would help if you
included this version string.

But you've got this right: pull the latest code, add the --v=1 flag to
your command-line, and keep monitoring the job, to catch it if it
crashes again.

Keep an eye on the log size, as well, it *will* grow a lot! :-)

**Comment by tedwang2015** [comment] 2015-07-13 09:50
Thanks a lot.
Already update the build today. Let’s monitor for a while.

**Comment by tedwang2015** [comment] 2015-07-15 06:14
Hi Mark, 

Today my Server crash again. 
Server version
ct-server version 7755371ff02e696fea5978367012b8560b562a17

I have the log file, is there any way that can transfer the log to you 

Best wishes
Ted

**Comment by tedwang2015** [comment] 2015-07-15 07:26
Log Upload here
https://groups.google.com/forum/?fromgroups#!topic/certificate-transparency/Q9UqKijlp8A

**Comment by pphaneuf** [comment] 2015-07-15 09:12
You sent in the WARNING log file, which has a hint of what happened (tried to watch a non-existent etcd key, I think?), but the INFO log would be more informative.

Could you send just the last 10,000 lines and compress them, to save space?

    tail -n 10000 ct-server.INFO | gzip > ct-server-log.gz

I've also made a pull request to improve that last fatal log line, to have it say which etcd key caused the crash, I'll update this issue when it is merged, so you can pull the improved version.

**Comment by tedwang2015** [comment] 2015-07-15 09:20
Hi

Thanks a lot.
I have upload the info log, please check


Best wishes
Ted

**Comment by pphaneuf** [comment] 2015-07-15 09:21
Here's some of the logs from the currently posted file:

```
W0713 12:22:48.617786  9997 etcd_consistent_store-inl.h:893] Etcd stats fetch failed: UNAVAILABLE: connection failed.
W0713 21:22:12.952247 10257 cluster_state_controller-inl.h:265] Couldn't set ClusterNodeState: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 00:07:02.952371 10257 cluster_state_controller-inl.h:265] Couldn't set ClusterNodeState: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 00:07:03.452728 10258 ct-server.cc:267] Problem sequencing new entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 00:07:03.452761 10259 etcd_consistent_store-inl.h:828] Couldn't get sequence mapping: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 00:07:03.452924 10259 ct-server.cc:234] Problem cleaning up old entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 06:06:24.986661 10258 ct-server.cc:267] Problem sequencing new entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 16:16:03.452591 10259 etcd_consistent_store-inl.h:828] Couldn't get sequence mapping: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 16:16:03.452599 10258 ct-server.cc:267] Problem sequencing new entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 16:16:03.452746 10259 ct-server.cc:234] Problem cleaning up old entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 17:07:52.952388 10257 cluster_state_controller-inl.h:265] Couldn't set ClusterNodeState: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 17:07:53.452425 10259 etcd_consistent_store-inl.h:828] Couldn't get sequence mapping: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 17:07:53.452448 10258 ct-server.cc:267] Problem sequencing new entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
W0714 17:07:53.452544 10259 ct-server.cc:234] Problem cleaning up old entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
F0714 18:07:21.684504  9993 etcd.cc:477] Check failed: task->status().ok() initial get error: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
```

@AlCutter, I'm a bit surprised there's as much of the `Invalid JSON: Couldn't find 'node'` error, I thought your error reporting change should have changed this to be clearer?

**Comment by pphaneuf** [comment] 2015-07-15 09:50
@AlCutter: From my reading of `FetchDone`, if we get this error message, it means that `StatusFromResponse` deemed the request overall successful? Speciflcally, I'm not sure in which case you'd get a response that has a correctly parsed JSON, HTTP status 200, no `errorCode` in the JSON, *but* no `node` either?!?

I just tried getting a non-existent key here, and I get this (with HTTP status 404):

```json
{
   "cause" : "/foo",
   "errorCode" : 100,
   "index" : 2,
   "message" : "Key not found"
}
```

**Comment by pphaneuf** [comment] 2015-07-15 09:51
@tedwang2015: By the way, which version of etcd are you running?

**Comment by AlCutter** [comment] 2015-07-15 10:00
Hi Ted,

It looks a little like might be a connectivity issue or etcd is not
listening all the time/crashing or *something; *there are a number of lines
like this in the log:
   Releasing errored connection to 10.42.212.50:2379
which suggest that something is not quite right.

I think generally the log struggles on and copes with whatever is
happening, until such time as the initial get for a watch errors out, when
it CHECK fails as you've seen.

Regardless, the CHECK crash is wrong and in fact I believe there's a TODO (with
Pierre's name on it, no less :) at that line to handle it better.

I'll see if one of us can fix that today for you which should help a
little, but there definitely seems to be some underlying problem which
needs to be looked into.

Cheers,
Al.


On Wed, Jul 15, 2015 at 10:20 AM, tedwang2015 <notifications@github.com>
wrote:

> Hi
>
> Thanks a lot.
> I have upload the info log, please check
>
>
> Best wishes
> Ted
> From: Pierre Phaneuf [mailto:notifications@github.com]
> Sent: 2015年7月15日 17:12
> To: google/certificate-transparency
> Cc: Ted Wang (RD-CN)
> Subject: Re: [certificate-transparency] The log server frequently crash
> when the master election. (#811)
>
>
> You sent in the WARNING log file, which has a hint of what happened (tried
> to watch a non-existent etcd key, I think?), but the INFO log would be more
> informative.
>
> Could you send just the last 10,000 lines and compress them, to save
> space?
>
> tail -n 10000 ct-server.INFO | gzip > ct-server-log.gz
>
> I've also made a pull request to improve that last fatal log line, to have
> it say which etcd key caused the crash, I'll update this issue when it is
> merged, so you can pull the improved version.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/google/certificate-transparency/issues/811#issuecomment-121539845>.
>
>
> =======================================================
>
> This message has been analyzed by Deep Discovery Email Inspector.
>
>
>
> <table class="TM_EMAIL_NOTICE"><tr><td><pre>
> TREND MICRO EMAIL NOTICE
> The information contained in this email and any attachments is
> confidential
> and may be subject to copyright or other intellectual property protection.
> If you are not the intended recipient, you are not authorized to use or
> disclose this information, and we request that you notify us by reply mail
> or
> telephone and delete the original message from your mail system.
> </pre></td></tr></table>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/certificate-transparency/issues/811#issuecomment-121544566>
> .
>



-- 
Google UK Ltd | 123 Buckingham Palace Road | London SW1W 9SH | Registered
in England Number: 3977902

**Comment by pphaneuf** [comment] 2015-07-15 10:04
I did think of the option of "just fix the TODO next to the CHECK", but I'm thinking that there's something here that we don't understand going on, I'd like to understand it a bit better, before we "make it go away"?

If this "no 'node' key" is not supposed to happen at all, maybe we could just dump the whole JSON response in that case? If only temporarily, as a debugging aid...

**Comment by AlCutter** [comment] 2015-07-15 10:14
Also, adding a `--vmodule="etcd=2"` flag should get the response body from all successful etcd requests.

**Comment by tedwang2015** [comment] 2015-07-16 02:18
This is my ETCD version. 
[root@tmssl-prod-ct01 etcd]# ./etcd --version
etcd Version: 2.0.11
Git SHA: 0678329
Go Version: go1.4.2
Go OS/Arch: linux/amd64

**Comment by tedwang2015** [comment] 2015-07-16 02:20
My ETCD cluster is working. 
[root@tmssl-prod-ct01 etcd]# ./etcdctl cluster-health
cluster is healthy
member 68c3d3827e333b02 is unhealthy
member 7c5b79cd8e53e10d is healthy
member ba1f1406c722a7de is healthy

Next action, I would enable high level log and pull the latest code.

**Comment by tedwang2015** [comment] 2015-07-16 02:36
The new version I have 
ct-server version fff70d4688023b11a735cbd53f9fb655d5c50c6d


opt/hydra/ctlog/ct-server --server=10.42.212.50 --port=8124 --key=/opt/hydra/ctlog/logsigner.hydra.trendmicro.com.pem --trusted_cert_file=/opt/hydra/ctlog/trusted-cert.pem --logtostderr=false --tree_signing_frequency_seconds=600 --sqlite_db=/opt/hydra/ctlog/storage/ct --log_dir=/opt/hydra/ctlog/log --etcd_host=10.42.212.50 --etcd_port=2379 --v=2


Best wishes
Ted

**Comment by AlCutter** [comment] 2015-07-16 06:42
On 16 Jul 2015 3:20 am, "tedwang2015" <notifications@github.com> wrote:
>
> My ETCD cluster is working.
> [root@tmssl-prod-ct01 etcd]# ./etcdctl cluster-health
> cluster is healthy
> member 68c3d3827e333b02 is unhealthy

This node doesn't look so good :)

> member 7c5b79cd8e53e10d is healthy
> member ba1f1406c722a7de is healthy
>
> Next action, I would enable high level log and pull the latest code.

That'll have check which killed your log removed, but we still think
there's some underlying problem.  There shouldn't be so many errored
connections...

It might be worth running a wireshark capture too to see if we can better
understand what's happening with those?

Incidentally, there's a 2.0.13 release of etcd.

**Comment by tedwang2015** [comment] 2015-07-16 07:13
Yes, the node is 68c3d3827e333b02 is actually unavailable. It should not impact the business. ☺

I can run tcpdump, but can you let me know to command that you want me to run on that server.


Best wishes
Ted

**Comment by AlCutter** [comment] 2015-07-16 08:22
On 16 Jul 2015 8:13 am, "tedwang2015" <notifications@github.com> wrote:
>
>
> Yes, the node is 68c3d3827e333b02 is actually unavailable. It should not
impact the business. ☺
>
> I can run tcpdump, but can you let me know to command that you want me to
run on that server.

I guess for now just do whatever you were doing before when it crashed?

>
>
> Best wishes
> Ted
> From: Al Cutter [mailto:notifications@github.com]
> Sent: 2015年7月16日 14:43
> To: google/certificate-transparency
> Cc: Ted Wang (RD-CN)
> Subject: Re: [certificate-transparency] The log server frequently crash
when the master election. (#811)
>
> On 16 Jul 2015 3:20 am, "tedwang2015" <notifications@github.com<mailto:
notifications@github.com>> wrote:
> >
> > My ETCD cluster is working.
> > [root@tmssl-prod-ct01 etcd]# ./etcdctl cluster-health
> > cluster is healthy
> > member 68c3d3827e333b02 is unhealthy
>
> This node doesn't look so good :)
>
> > member 7c5b79cd8e53e10d is healthy
> > member ba1f1406c722a7de is healthy
> >
> > Next action, I would enable high level log and pull the latest code.
>
> That'll have check which killed your log removed, but we still think
> there's some underlying problem. There shouldn't be so many errored
> connections...
>
> It might be worth running a wireshark capture too to see if we can better
> understand what's happening with those?
>
> Incidentally, there's a 2.0.13 release of etcd.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
>
>
> —
> Reply to this email directly or view it on GitHub<
https://github.com/google/certificate-transparency/issues/811#issuecomment-121849305>.

>
> =======================================================
>
> This message has been analyzed by Deep Discovery Email Inspector.
>
>
>
> <table class="TM_EMAIL_NOTICE"><tr><td><pre>
> TREND MICRO EMAIL NOTICE
> The information contained in this email and any attachments is
confidential
> and may be subject to copyright or other intellectual property
protection.
> If you are not the intended recipient, you are not authorized to use or
> disclose this information, and we request that you notify us by reply
mail or

**Comment by tedwang2015** [comment] 2015-07-16 08:26
we are running the performance test on this. Keeping post the to addChain URL.

**Comment by tedwang2015** [comment] 2015-07-23 07:48
should I set -etcd_connection_timeout_seconds to bigger one to avoid the ETCD connection issue

**Comment by tedwang2015** [comment] 2015-07-23 09:41
Crash again. but seems different. 

because its timestamp is <= current serving STH timestamp (1437642712471)
I0723 09:16:22.453227 31225 cluster_state_controller-inl.h:499] Continuing to serve previous STH.
I0723 09:16:22.453280 31225 etcd.cc:426] path query: /v2/keys/root/nodes/?consistent=true&quorum=false&recursive=true&wait=true&waitIndex=1829075
I0723 09:16:22.453335 31225 connection_pool.cc:273] cached evhtp_connection for 10.42.212.50:2379
I0723 09:16:22.453387 31223 url_fetcher.cc:157] evhtp_make_request(0x7fa2a0003ac0, 0x174856a0, 0, "/v2/keys/root/nodes/?consistent=true&quorum=false&recursive=true&wait=true&waitIndex=1829075")
I0723 09:16:22.458299 31262 etcd.cc:426] path query: /v2/keys/root/sequence_mapping?consistent=true&quorum=true
I0723 09:16:22.458374 31263 etcd_consistent_store-inl.h:822] Cleaning old entries up to and including sequence number: 1349537
I0723 09:16:22.458376 31231 connection_pool.cc:273] cached evhtp_connection for 10.42.212.50:2379
I0723 09:16:22.458423 31263 etcd.cc:426] path query: /v2/keys/root/sequence_mapping?consistent=true&quorum=true
I0723 09:16:22.458426 31223 url_fetcher.cc:157] evhtp_make_request(0x7fa2a0001cf0, 0x174850c0, 0, "/v2/keys/root/sequence_mapping?consistent=true&quorum=true")
I0723 09:16:22.458451 31223 connection_pool.cc:197] Releasing errored connection to 10.42.212.50:2379
I0723 09:16:22.458456 31223 connection_pool.cc:295] returned Connection for 10.42.212.50:2379
I0723 09:16:22.458466 31223 connection_pool.cc:302] ConnectionPool for 10.42.212.50:2379 size : 3
I0723 09:16:22.458483 31229 connection_pool.cc:273] cached evhtp_connection for 10.42.212.50:2379
I0723 09:16:22.458536 31224 etcd.cc:688] EtcdClient::FetchDone: UNAVAILABLE: connection failed
F0723 09:16:22.458509 31229 connection_pool.cc:277] Check failed: 'retval->connection()' Must be non NULL 
I0723 09:16:22.458653 31227 etcd.cc:426] path query: /v2/keys/root/cluster_config?consistent=true&quorum=false&recursive=true&wait=true&waitIndex=1828740

Best wishes

**Comment by tedwang2015** [comment] 2015-07-30 09:06
I have some new findings, when the crash happen, the ETCD cluster status is unhealthy. 
However the ETCD self recovered, but ct-server is stooped.

**Comment by AlCutter** [comment] 2015-07-30 09:40
Great! 
This is interesting - as I mentioned it was clear that there had to be some external (to the log) issue causing this, but it's great to know exactly what the trigger was.

I'll try to reproduce it locally and see if we can figure out where the failure is.

BTW, when your cluster was unhealthy, do you know if it was refusing connections, accepting them but not responding, or accepting and returning some sort of error? (Not sure if there are different responses from etcd depending on the reason for the unhealthiness.)

**Comment by tedwang2015** [comment] 2015-07-31 05:14
OK Thanks. Will try to find more information

**Comment by tedwang2015** [comment] 2015-08-07 08:20
body: <<EOF
{"message":"Internal Server Error"}EOF
I0807 08:09:20.773484  2995 json_wrapper.h:130] No errorCode field
I0807 08:09:23.560768  3019 etcd.cc:430] path query: /v2/keys/root/nodes/9f7bfe5a-d52d-4c9a-a815-db59d2d5fb7b
I0807 08:09:24.249389  2990 connection_pool.cc:348] returned Connection for 10.42.212.51:2379
I0807 08:09:24.249420  2990 connection_pool.cc:355] ConnectionPool for 10.42.212.51:2379 size : 3
I0807 08:09:24.249467  2996 connection_pool.cc:317] cached evhtp_connection for 10.42.212.51:2379
I0807 08:09:24.249498  2995 connection_pool.cc:317] cached evhtp_connection for 10.42.212.51:2379
I0807 08:09:24.249536  2993 etcd.cc:721] EtcdClient::FetchDone: OK
I0807 08:09:24.249547  2993 etcd.cc:739] response:
status_code: 200
headers {
  Content-Length: 35
  Content-Type: application/json
  Date: Fri, 07 Aug 2015 08:09:20 GMT
  X-Etcd-Cluster-Id: d036c7ee65623f75
}
I0807 08:09:24.249567  2993 json_wrapper.h:130] No errorCode field
I0807 08:09:24.249604  2993 json_wrapper.h:130] No node field
W0807 08:09:24.249689  3021 ct-server.cc:268] Problem sequencing new entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
I0807 08:09:24.249835  2994 etcd.cc:739] response:
status_code: 200
headers {
  Content-Length: 35
  Content-Type: application/json
  Date: Fri, 07 Aug 2015 08:09:20 GMT
  X-Etcd-Cluster-Id: d036c7ee65623f75
}
body: <<EOF
{"message":"Internal Server Error"}EOF
I0807 08:09:24.249846  2990 connection_pool.cc:355] ConnectionPool for 10.42.212.51:2379 size : 4
I0807 08:09:24.249857  2994 json_wrapper.h:130] No errorCode field
I0807 08:09:24.249905  2994 json_wrapper.h:130] No node field
  Content-Length: 35
I0807 08:09:24.249604  2993 json_wrapper.h:130] No node field
W0807 08:09:24.249689  3021 ct-server.cc:268] Problem sequencing new entries: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'
I0807 08:09:24.249835  2994 etcd.cc:739] response:
status_code: 200
headers {
  Content-Length: 35
  Content-Type: application/json
  Date: Fri, 07 Aug 2015 08:09:20 GMT
  X-Etcd-Cluster-Id: d036c7ee65623f75
}
body: <<EOF
{"message":"Internal Server Error"}EOF
I0807 08:09:24.249846  2990 connection_pool.cc:355] ConnectionPool for 10.42.212.51:2379 size : 4
I0807 08:09:24.249857  2994 json_wrapper.h:130] No errorCode field
I0807 08:09:24.249905  2994 json_wrapper.h:130] No node field
  Content-Length: 35
  X-Etcd-Cluster-Id: d036c7ee65623f75
}
body: <<EOF
{"message":"Internal Server Error"}EOF
I0807 08:09:24.249971  2992 json_wrapper.h:130] No errorCode field
I0807 08:09:24.249996  2992 json_wrapper.h:130] No node field
I0807 08:09:24.250005  2994 etcd.cc:430] path query: /v2/stats/store?consistent=true&quorum=true
I0807 08:09:24.250018  3007 etcd.cc:430] path query: /v2/keys/root/entries/04c90ac088ff66cfbb465b773269fc8fe1c0f6c6d18138bc7f4b9932fdd1ad90?consistent=true&quorum=true
I0807 08:09:24.250051  2993 connection_pool.cc:317] cached evhtp_connection for 10.42.212.51:2379
I0807 08:09:24.250078  2998 connection_pool.cc:317] cached evhtp_connection for 10.42.212.51:2379
I0807 08:09:24.250085  3010 etcd.cc:430] path query: /v2/keys/root/entries/9e320f7be8d5f35985a4dcbff66c45a82835bacf7a15babdcc0af97bc313609f?consistent=true&quorum=true
I0807 08:09:24.250160  2995 connection_pool.cc:317] cached evhtp_connection for 10.42.212.51:2379
I0807 08:09:24.250254  2990 url_fetcher.cc:157] evhtp_make_request(0x7ffa14006c50, 0x2316d60, 3, "/v2/keys/root/nodes/9f7bfe5a-d52d-4c9a-a815-db59d2d5fb7b")
I0807 08:09:24.250283  2990 url_fetcher.cc:157] evhtp_make_request(0x7ffa1807e700, 0x10f59d0, 4, "/v2/keys/root/entries/186b40da130070caf40a503641885e3ce52f42a2b61dbfe8f2c6261a904bd5e8?consistent=true&quorum=true")
I0807 08:09:24.250301  2990 etcd.cc:721] EtcdClient::FetchDone: OK
I0807 08:09:24.250306  2990 etcd.cc:739] response:
status_code: 200
headers {
  Content-Length: 35
  Content-Type: application/json
  Date: Fri, 07 Aug 2015 08:09:21 GMT
  X-Etcd-Cluster-Id: d036c7ee65623f75
}
body: <<EOF
{"message":"Internal Server Error"}EOF
I0807 08:09:24.250341  2990 json_wrapper.h:130] No errorCode field
I0807 08:09:24.250358  2990 url_fetcher.cc:157] evhtp_make_request(0x7ffa1807dfc0, 0x6bb8e10, 0, "/v2/stats/store?consistent=true&quorum=true")
I0807 08:09:24.250373  2990 url_fetcher.cc:157] evhtp_make_request(0x7ffa1c0cf4f0, 0x3367ff0, 0, "/v2/keys/root/entries/04c90ac088ff66cfbb465b773269fc8fe1c0f6c6d18138bc7f4b9932fdd1ad90?consistent=true&quorum=true")
I0807 08:09:24.250386  2990 url_fetcher.cc:157] evhtp_make_request(0x7ffa140463d0, 0xa793b60, 0, "/v2/keys/root/entries/9e320f7be8d5f35985a4dcbff66c45a82835bacf7a15babdcc0af97bc313609f?consistent=true&quorum=true")
I0807 08:09:24.250403  2990 json_wrapper.h:130] No node field
F0807 08:09:24.250430  2990 masterelection.cc:362] Check failed: task->status().ok() /root/election/9f7bfe5a-d52d-4c9a-a815-db59d2d5fb7b: FAILED_PRECONDITION: Invalid JSON: Couldn't find 'node'

**Comment by tedwang2015** [comment] 2015-08-07 08:54
is there way to torrent this? each time after, I check the etcd, it is healthy. And I also a a parallel machine, it has no problem which connection the same etcd cluster

**Comment by tedwang2015** [comment] 2015-08-07 10:09
BTW, there are a lot of request add-chain request, will it overload on the ETCD. 
I tune some parameter, hope it will help. 
 --etcd_connection_timeout_seconds=30 --node_state_ttl_seconds=180 --master_keepalive_interval_seconds=240

Best wishes
Ted

**Comment by pphaneuf** [comment] 2015-08-07 16:15
What version of ct-server is this? The log message for the response is very odd, with an error message, but status 200 (OK)...

What version of etcd (`etcd --version` should tell, I think) is this?  How many nodes do you have in the etcd cluster? And in your ct-server cluster? What version of the Go compiler (`go version`) did you compile etcd with?

I'm not sure what you mean by "torrent this"?

I think those flags you tuned should make sense and make it more tolerant to glitches from etcd.

In our test setup on Google Cloud Engine, using the scripts in the `cloud` directory, we've done close to 400 add-chain requests per second, submitting the entire content of the Pilot log (about 8 million log entries), without a single error, which is why we're quite curious of what could be causing problems in your setup (since it's so smooth for us).

There is some problems with high memory usage in etcd when doing a lot of submissions, because it has to keep all its data in memory. It's not a big problem, but we did put the `etcd_reject_add_pending_threshold` in the `ClusterConfig` (defaulting to 30000), which causes ct-server to reject add-chain/add-pre-chain requests when there are more than that number of entries in etcd. In our load testing, that limit would be reached constantly, but we adapted our load submission client to retry after a small delay, and it did not cause any problems.

But I know that newer Go runtimes have better garbage collection and memory management, with fewer pauses, and more efficient memory usage, I suspect than an etcd compiled with an older version might not be as robust?

**Comment by tedwang2015** [comment] 2015-08-08 08:16
Hi @pphaneuf 

Thank you very much. I did not compile any ETCD with go.  

This is how I got etcd.
curl -L  https://github.com/coreos/etcd/releases/download/v2.1.1/etcd-v2.1.1-linux-amd64.tar.gz -o etcd-v2.1.1-linux-amd64.tar.gz
tar xzvf etcd-v2.1.1-linux-amd64.tar.gz
cd etcd-v2.1.1-linux-amd64

ct-server version 4717f34d66f6a23d82deec68c75e929959681455

The I running 2 Node ct-server , A and B
And Node A, I host two ETCD, and on B I Host 1 ETCD. 


etcd Version: 2.1.1
Git SHA: 6335fdc
Go Version: go1.4.2
Go OS/Arch: linux/amd64

Trying to monitor for a while. 

Best wishes
Ted

**Comment by pphaneuf** [comment] 2015-08-10 16:02
The version of etcd that we have tested with appears to be v2.0.9:

https://github.com/coreos/etcd/releases/download/v2.0.9/etcd-v2.0.9-linux-amd64.tar.gz

This is taken from here:

https://github.com/google/certificate-transparency/blob/master/cloud/etcd/Dockerfile

Note that it's not of much use to run more than one etcd on the same server. And you might have seen that it is not that useful to run two nodes (you cannot tolerate any failure, so no improvement compared to one node, but at least you get a backup of the etcd data).

The version of ct-server is very recent, but the log messages are inconsistent with what it should be, this is very strange!

For example, an error message from etcd is supposed to be JSON containing "message" and "code, but yours looks like this:

```json
{"message":"Internal Server Error"}
```

No trace of "code"? Something looks wrong from etcd...

**Comment by tedwang2015** [comment] 2015-08-11 02:14
@pphaneuf 

Many thanks.  

The ETCD is running as three nodes cluster which I host two of them on one machine. Later on I move on to a new machine. 

./etcdctl  cluster-health
cluster is healthy
member 7866f5461141244a is healthy
member 8ea0a67758e768d2 is healthy
member fc212660bd503048 is healthy
[root@tmssl-prod-ct02 etcd]# ./etcdctl member list
7866f5461141244a: name=etcd_ct0 peerURLs=http://10.42.212.50:2380 clientURLs=http://10.42.212.50:2379
8ea0a67758e768d2: name=etcd_ct1 peerURLs=http://10.42.212.51:2380 clientURLs=http://10.42.212.51:2379
fc212660bd503048: name=etcd_ct2 peerURLs=http://10.42.212.50:3380 clientURLs=http://10.42.212.50:3379

Best wishes
Ted

**Comment by tedwang2015** [comment] 2015-08-11 02:23
Also tune the parameter of the ct log.
--etcd_servers=10.42.212.50:2379,10.42.212.51:2379,10.42.212.50:3379 --v=2 --etcd_connection_timeout_seconds=30 --node_state_ttl_seconds=900 --master_keepalive_interval_seconds=240


And  I did see some error, while 

Like this. 
E0811 01:47:36.877425 11012 etcd_consistent_store-inl.h:307] Couldn't create or fetch /root/entries/8cc96b8f9b61d3e13fa944cab59c247a2e74bc2a04b31d1aaf9c3f9faf6d0cbc : NOT_FOUND: Etcd message: Key not found, cause: /root/entries/8cc96b8f9b61d3e13fa944cab59c247a2e74bc2a04b31d1aaf9c3f9faf6d0cbc (/root/entries/8cc96b8f9b61d3e13fa944cab59c247a2e74bc2a04b31d1aaf9c3f9faf6d0cbc)
I0811 01:47:36.877704 11012 handler.cc:124] error adding chain: NOT_FOUND: Etcd message: Key not found, cause: /root/entries/8cc96b8f9b61d3e13fa944cab59c247a2e74bc2a04b31d1aaf9c3f9faf6d0cbc (/root/entries/8cc96b8f9b61d3e13fa944cab59c247a2e74bc2a04b31d1aaf9c3f9faf6d0cbc)
I0811 01:47:36.877811 11000 json_output.cc:94] 127.0.0.1 "POST /ct/v1/add-chain" 400 242

And I found some error on the etcd logs. 

2015/08/11 01:47:36 etcdhttp: got unexpected response error (etcdserver: request timed out)
2015/08/11 01:47:36 etcdhttp: got unexpected response error (etcdserver: request timed out)
2015/08/11 01:47:37 etcdhttp: got unexpected response error (etcdserver: request timed out)
2015/08/11 01:47:37 etcdhttp: got unexpected response error (etcdserver: request timed out)


Good news is the CT Server seems no stable. 

But I am not sure how to avoid the error occur.  

Best wishes
Ted

**Comment by tedwang2015** [comment] 2015-08-11 02:37
These are my etcd initial parameter. 
2015/08/8 08:00:59 etcdserver: recovered store from snapshot at index 1291301
2015/08/8 08:00:59 etcdserver: name = etcd_ct0
2015/08/8 08:00:59 etcdserver: data dir = etcd_ct0.etcd
2015/08/8 08:00:59 etcdserver: member dir = etcd_ct0.etcd/member
2015/08/8 08:00:59 etcdserver: heartbeat = 100ms
2015/08/8 08:00:59 etcdserver: election = 1000ms

I saw in the dock file it is 6000ms for the election.  if this would help I would like to  try. 


Best wishes
Ted

**Comment by tedwang2015** [comment] 2015-08-18 02:54
@pphaneuf,

Thank you very much for helping on this case.  With the following parameter, the ct server is more stable now. 
--etcd_connection_timeout_seconds=30 --node_state_ttl_seconds=900 --master_keepalive_interval_seconds=240

If no problem, I am going to close this case. 

Best wishes
Ted

**Comment by pphaneuf** [comment] 2015-08-18 12:23
If it's working for you, no problem! Feel free to open another issue if you have other problems.

**Closed by pphaneuf** 2015-08-18 12:23 UTC
