### ISSUE TITLE
Please Please help me

### ISSUE THREAD

**Issue by homepc91** [google/certificate-transparency#1426] opened 2017-11-20 11:43 UTC
Hi, Everyone's please please help me and help to solved this problem

1. My 1st Problem is :- When I run ./prepare_etcd.sh, I am getting error in last line :-> "W1013 07:02:03.298388 528384 etcd.cc:798] Got invalid JSON:**"

2. My 2nd Problem is :- How to get Base64 Log ID..?

![32977192-652c676c-cc4e-11e7-8477-aa195f51f1b6](https://user-images.githubusercontent.com/25889886/33016842-05825d3e-ce16-11e7-92ab-c412d2da37d5.png)

Please Please help me

thanks

**Comment by AlCutter** [comment] 2017-11-20 11:53
Duplicate of #1423

**Closed by AlCutter** 2017-11-20 11:53 UTC
